name: "Build"
on:
  push:
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read  # permits an action to list the commits (unsure if necessary for us)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Pull our repository
      - name: Checkout
        uses: actions/checkout@v3
        # with:
          # fetch-depth: 0
          # submodules: true
          # If using the 'assets' git submodule from Chirpy Starter, uncomment above
          # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

      - name: Debug
        # confirmed that rsync is installed
        run: |
          echo "Debugging..."

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
          bundler-cache: true

      - name: Build site
        run: |
          pwd
          ls -lah
          echo $JEKYLL_ENV
          which git
          bundle exec jekyll b
          ls -lah
          ls -lah _site
        env:
          JEKYLL_ENV: "production"

      - name: Test site
        run: |
          ls -alh
          ls -lah _site
          bundle exec htmlproofer _site --disable-external --check-html --ignore-urls http://www.mathmatique.com/articles/left-exercise-reader

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "_site"

      - name: Dry-run deployment to mattpopovich.com
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          ARGS: "-ahv --delete --dry-run"
          SOURCE: "_site/"
          TARGET: ${{ secrets.SERVER_DESTINATION }}
          SCRIPT_BEFORE: |
            whoami
            ls -lah
          SCRIPT_AFTER: |
            whoami
            ls -lah
            ls -lah mattpopovich.com
