name: "Build"
on:
  push:
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read  # permits an action to list the commits (unsure if necessary for us)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Pull our repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # for posts's lastmod
          # submodules: true
          # If using the 'assets' git submodule from Chirpy Starter, uncomment above
          # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3 # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
          bundler-cache: true

      - name: Build site
        run: |
          bundle exec jekyll b
        env:
          JEKYLL_ENV: "production"

      - name: Test site
        run: |
          bundle exec htmlproofer _site \
            \-\-disable-external \
            \-\-ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/,http://www.mathmatique.com/articles/left-exercise-reader"

      - name: Dry-run deployment to mattpopovich.com
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          ARGS: "-ahv --delete --dry-run"
          SOURCE: "_site/"
          TARGET: ${{ secrets.SERVER_DESTINATION }}
          SCRIPT_BEFORE: |
            whoami
            ls -lah
          SCRIPT_AFTER: |
            whoami
            ls -lah
            ls -lah mattpopovich.com
